2025-08-03 23:19:01,762 - my_logger - ERROR - 添加数据错误! 模型: <class 'model.models.model.Monthes'> 数据: {'curd': {'fuk_dan': Decimal('57969'), 'user_bank_name': '', 'user_bank_number': '', 'user_name': 'Oseni Ibrahim', 'card_type': 'Razer', 'card_country': 'USA', 'card_code': '15563082346563', 'card_balance': Decimal('50'), 'card_rate': Decimal('5.4')}, 'is_commit': True} 报错信息: (psycopg2.errors.NotNullViolation) null value in column "work_type" of relation "monthes" violates not-null constraint
DETAIL:  Failing row contains (3, 5c523e39af5c4b36a3c532baa7f600b9, null, null, null, null, Oseni Ibrahim, Razer, USA, 15563082346563, 57969.00, , , 50.00, 5.40, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, null, null, 0, 2025-08-03 23:18:16.052291, 2025-08-03 23:18:16.052414).

[SQL: INSERT INTO monthes (uuid, work_type, serial, auth_name, equipment, user_name, card_type, card_country, card_code, fuk_dan, user_bank_name, user_bank_number, card_balance, card_rate, acquisition, selling, rate, handling, naila_balance, money, channel, img, status, create_time, update_time) VALUES (%(uuid)s, %(work_type)s, %(serial)s, %(auth_name)s, %(equipment)s, %(user_name)s, %(card_type)s, %(card_country)s, %(card_code)s, %(fuk_dan)s, %(user_bank_name)s, %(user_bank_number)s, %(card_balance)s, %(card_rate)s, %(acquisition)s, %(selling)s, %(rate)s, %(handling)s, %(naila_balance)s, %(money)s, %(channel)s, %(img)s, %(status)s, %(create_time)s, %(update_time)s) RETURNING monthes.id]
[parameters: {'uuid': '5c523e39af5c4b36a3c532baa7f600b9', 'work_type': None, 'serial': None, 'auth_name': None, 'equipment': None, 'user_name': 'Oseni Ibrahim', 'card_type': 'Razer', 'card_country': 'USA', 'card_code': '15563082346563', 'fuk_dan': Decimal('57969'), 'user_bank_name': '', 'user_bank_number': '', 'card_balance': Decimal('50'), 'card_rate': Decimal('5.4'), 'acquisition': Decimal('0.00'), 'selling': Decimal('0.00'), 'rate': Decimal('0.00'), 'handling': Decimal('0.00'), 'naila_balance': Decimal('0.00'), 'money': Decimal('0.00'), 'channel': None, 'img': None, 'status': 0, 'create_time': datetime.datetime(2025, 8, 3, 23, 18, 16, 52291), 'update_time': datetime.datetime(2025, 8, 3, 23, 18, 16, 52414)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
